print("------ My ID Card ------")
name=input("Enter Name: ")
roll =input("Enter Roll No:")
blood =input("Enter Blood Group: ")
DOB = input("Enter DOB:")
College=input("Enter College Name:")
City = input("Enter City:")
Address=input("Enter Address: ")

print("------ Student ID Card ------")
print("Name: ",name)
print("Roll no: ",roll)
print("Blood Group: ",blood)
print("DOB: ",DOB)
print("College Name: ",College)
print("City: ",City)
print("Address: ",Address)